### ISSUE TITLE
ItemPostCustomerPost

### ISSUE THREAD

**Issue by skyla00** [skyla00/EVision-app#337]
## Purpose
 > ItemPostCustomerPost

## Details

- [ ] 등록 시 이미 존재하는 item code 이면 오류메시지 전송
- [ ] 삭제 로직 짜기. 

## Estimated working time

-  2 hr

**Comment by KERERCVASD** [comment]
I think this will help you.
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)
